- hosts: dockerserver
  tasks:
    - name: Start the docker service
      command: sudo service docker start
      ignore_errors: yes

    - name: Register all docker containers id are running
      command: sudo docker ps -aq
      register: dockerContainerIds

    - name: Register all current docker images id
      command: sudo docker images -aq
      register: dockerImagesIds

    - name: Stop all containers
      command: "sudo docker stop rmitstore"
      ignore_errors: yes

    - name: Remove all containers
      command: "sudo docker rm rmitstore"
      ignore_errors: yes

    - name: Remove all images
      command: "sudo docker rmi --force 3750945/rmitstore:latest"
      ignore_errors: yes

    - name: Log out if connected to Docker
      command: sudo docker logout
      ignore_errors: yes

    - name: Run the apache container based on pushed docker hub image
      command: sudo docker run -d --name rmitstore --rm -p 80:80 3750945/rmitstore:latest