---
- name: Configure Docker Swarm Nodes
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

- name: Setup Manager Node
  hosts: manager
  become: yes
  tasks:
    - name: Initialize Docker Swarm
      command: docker swarm init

- name: Setup Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Join Swarm Cluster
      command: docker swarm join --token "{{ hostvars['manager']['swarm_token'] }}" "{{ hostvars['manager']['ansible_eth0']['ipv4']['address'] }}:2377"
      when: "'swarm_token' in hostvars['manager']"
