apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    name: mariadb-pod
    app: demo-store-app
spec:
  containers:
  - name: mariadb
    image: 959445117732.dkr.ecr.us-east-1.amazonaws.com/mariadb
    env:
    - name: MYSQL_USER
      value: "mariadb"
    - name:  MYSQL_PASSWORD
      value: "mariadb"
    - name: MYSQL_ROOT_HOST
      value:
    - name: MYSQL_ROOT_PASSWORD
      value: "mariadb"
    ports:
     - containerPort: 3306