apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app-deploy
  labels:
    name: store-app-deploy
    app: demo-store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: store-app-pod
      app: demo-store-app
    
  template:
    metadata:
      name: store-app-pod
      labels:
        name: store-app-pod
        app: demo-store-app
    spec:
      containers:
        - name: store-app
          image: 959445117732.dkr.ecr.us-east-1.amazonaws.com/rmitstore
          ports:
            - containerPort: 80

    