apiVersion: v1
kind: Service
metadata:
  name: store-service
  labels:
    name: store-service
    app: demo-store-app
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: store-app-pod
     app: demo-store-app